### ISSUE TITLE
Axes labels are dark in Matplotlib plots in Tailwind-dark

### ISSUE THREAD

**Issue by nprav** [simicd/jupyterlab-tailwind-theme#12]
In JupyterLab with the Tailwind dark theme, when plotting matplotlib plots, the axes labels remain black. See comparisons between tailwind-dark and jupyterlab-dark below for eg.

I am using JupyterLab 2.1.4.

Great job on the theme!

![image](https://user-images.githubusercontent.com/7060774/88311334-c483cf00-ccde-11ea-88a3-308c35da0f60.png)
![image](https://user-images.githubusercontent.com/7060774/88311526-fa28b800-ccde-11ea-80d7-aa939e681e75.png)

**Comment by simicd** [comment]
Hi @nprav, thanks for the feedback and for reporting the issue! I looked into it and was able to replicate it. As proposed, I added white background as default so the axis becomes visible. I tried to make the axis color brighter but wasn't successful since this is controlled in Python code and not through css styles.

![image](https://user-images.githubusercontent.com/10134699/88591813-3c465680-d05d-11ea-8e53-0d75d006ff99.png)

**Comment by simicd** [comment]
On another note: Matplotlib also has a dark theme I figured out. By adding `plt.style.use('dark_background')` one can turn any chart into a dark mode compatible chart:

![image](https://user-images.githubusercontent.com/10134699/88591998-8e877780-d05d-11ea-8ecf-b1e8d94e3935.png)

**Comment by nprav** [comment]
I was not aware of the 'dark_background' option. I will certainly try it out. Your proposal looks great. Thanks!

**Comment by simicd** [comment]
@nprav Awesome, just published [v0.4.2 on npm](https://www.npmjs.com/package/jupyterlab-tailwind-theme) so it can be installed now - cheers!
